const { ROLES } = require("./roles");

const PERMISSIONS = Object.freeze({
  ADMIN_DASHBOARD_VIEW: "admin:dashboard:view",
  ADMIN_USERS_VIEW: "admin:users:view",
  ADMIN_USERS_MANAGE: "admin:users:manage",
  ADMIN_CAMPAIGNS_VIEW: "admin:campaigns:view",
  ADMIN_REPORTS_VIEW: "admin:reports:view",
  ADMIN_EARNINGS_VIEW: "admin:earnings:view",
  ADMIN_DISPUTES_VIEW: "admin:disputes:view",
  ADMIN_DISPUTES_MANAGE: "admin:disputes:manage",
  ADMIN_PAYMENTS_VIEW: "admin:payments:view",
  ADMIN_PAYMENTS_MANAGE: "admin:payments:manage",

  OWNER_DASHBOARD_VIEW: "owner:dashboard:view",
  OWNER_ADMINS_VIEW: "owner:admins:view",
  OWNER_ADMINS_MANAGE: "owner:admins:manage",
  OWNER_FINANCIAL_VIEW: "owner:financial:view",
  OWNER_FINANCIAL_MANAGE: "owner:financial:manage",
  OWNER_AUDIT_VIEW: "owner:audit:view",

  CAMPAIGN_CREATE: "campaign:create",
  CAMPAIGN_MANAGE_OWN: "campaign:manage:own",
  CAMPAIGN_VIEW: "campaign:view",

  BOOKING_CREATE: "booking:create",
  BOOKING_ACCESS_OWN: "booking:access:own",

  EARNING_VIEW_OWN: "earning:view:own",
  PROFILE_MANAGE_OWN: "profile:manage:own",
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.OWNER]: [
  PERMISSIONS.ADMIN_DASHBOARD_VIEW,
  PERMISSIONS.ADMIN_USERS_VIEW,
  PERMISSIONS.ADMIN_USERS_MANAGE,
  PERMISSIONS.ADMIN_CAMPAIGNS_VIEW,
  PERMISSIONS.ADMIN_REPORTS_VIEW,
  PERMISSIONS.ADMIN_EARNINGS_VIEW,
  PERMISSIONS.ADMIN_DISPUTES_VIEW,
  PERMISSIONS.ADMIN_DISPUTES_MANAGE,
  PERMISSIONS.ADMIN_PAYMENTS_VIEW,
  PERMISSIONS.ADMIN_PAYMENTS_MANAGE,

  PERMISSIONS.CAMPAIGN_VIEW,
  PERMISSIONS.CAMPAIGN_MANAGE_OWN,
  PERMISSIONS.BOOKING_ACCESS_OWN,
  PERMISSIONS.EARNING_VIEW_OWN,
  PERMISSIONS.PROFILE_MANAGE_OWN,

  PERMISSIONS.OWNER_DASHBOARD_VIEW,
  PERMISSIONS.OWNER_ADMINS_VIEW,
  PERMISSIONS.OWNER_ADMINS_MANAGE,
  PERMISSIONS.OWNER_FINANCIAL_VIEW,
  PERMISSIONS.OWNER_FINANCIAL_MANAGE,
  PERMISSIONS.OWNER_AUDIT_VIEW,
],
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_DASHBOARD_VIEW,
    PERMISSIONS.ADMIN_USERS_VIEW,
    PERMISSIONS.ADMIN_USERS_MANAGE,
    PERMISSIONS.ADMIN_CAMPAIGNS_VIEW,
    PERMISSIONS.ADMIN_REPORTS_VIEW,
    PERMISSIONS.ADMIN_EARNINGS_VIEW,
    PERMISSIONS.ADMIN_DISPUTES_VIEW,
    PERMISSIONS.ADMIN_DISPUTES_MANAGE,
    PERMISSIONS.ADMIN_PAYMENTS_VIEW,
    PERMISSIONS.ADMIN_PAYMENTS_MANAGE,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.CAMPAIGN_MANAGE_OWN,
    PERMISSIONS.BOOKING_ACCESS_OWN,
    PERMISSIONS.EARNING_VIEW_OWN,
    PERMISSIONS.PROFILE_MANAGE_OWN,
  ],
  [ROLES.MARKETER]: [
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_MANAGE_OWN,
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_ACCESS_OWN,
    PERMISSIONS.PROFILE_MANAGE_OWN,
  ],
  [ROLES.KOC]: [
    PERMISSIONS.CAMPAIGN_VIEW,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_ACCESS_OWN,
    PERMISSIONS.EARNING_VIEW_OWN,
    PERMISSIONS.PROFILE_MANAGE_OWN,
  ],
});

function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

function roleHasPermission(role, permission) {
  return getPermissionsForRole(role).includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsForRole,
  roleHasPermission,
};
